// =============================================================================
// test_rescore_pool_loader.cpp — serial-mapped complex coordinate loader.
//
// The offline pool rescoring engine (LIB/rescore_pool.cpp, hooked in top.cpp
// via FLEXAIDDS_RESCORE_POOL) restores FULL-complex coordinates from emitted
// pose files so optimisable DoF on both sides (receptor side chains + ligand
// torsions) are honoured exactly as docked. Correctness of the serial-to-slot
// mapping is therefore load-bearing: a swapped pair would silently rescore
// against wrong geometry. These tests pin the mapping contract on the inline
// loader (flexaids::load_complex_coor_from_pdb) with no engine state needed.
//
// Apache-2.0 (c) 2026 Le Bonhomme Pharma
// =============================================================================

#include "rescore_pool.h"

#include <gtest/gtest.h>

#include <cstdlib>
#include <fstream>
#include <string>
#include <unordered_map>

namespace {

const char* kPosePdb =
    "REMARK coordinate file generated by FlexAID\n"
    "ATOM      1  N   ALA A  42       1.000   2.000   3.000  1.00  0.00           N\n"
    "ATOM      5  CA  ALA A  42       4.000  -5.000   6.000  1.00  0.00           C\n"
    "HETATM  100  C1  LIG B   1      -7.000   8.000   9.000  1.00  0.00           C\n"
    "HETATM  101  O1  LIG B   1     -10.000 -11.000  12.000  1.00  0.00           O\n"
    "HETATM  102  O   HOH B  99     100.000 200.000 300.000  1.00  0.00           O\n"
    "CONECT  100  101\n"
    "END\n";

std::string write_temp(const std::string& name, const std::string& content)
{
    const char* td = std::getenv("TMPDIR");
    const std::string path =
        std::string(td && td[0] ? td : "/tmp") + "/" + name;
    std::ofstream ofs(path);
    ofs << content;
    return path;
}

} // namespace

TEST(RescorePoolLoader, MapsSerialsToSlotsAndSkipsUnknowns)
{
    // Deliberately sparse map: serial 5 is unmapped and must be SKIPPED, not
    // silently compacted — a compaction bug would shift every later atom.
    std::unordered_map<int,int> m{{1, 7}, {100, 0}, {102, 3}};
    float coor[4 * 3] = {};
    int matched = -1, skipped = -1;

    const std::string path = write_temp("rescore_loader_ok.pdb", kPosePdb);
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));

    EXPECT_EQ(matched, 3);
    EXPECT_EQ(skipped, 2);  // serial 5 unmapped + CONECT/END are not atom lines

    EXPECT_FLOAT_EQ(coor[7 * 3 + 0], 1.0f);   // serial 1 -> slot 7
    EXPECT_FLOAT_EQ(coor[7 * 3 + 1], 2.0f);
    EXPECT_FLOAT_EQ(coor[7 * 3 + 2], 3.0f);

    EXPECT_FLOAT_EQ(coor[0 * 3 + 0], -7.0f);  // serial 100 -> slot 0
    EXPECT_FLOAT_EQ(coor[0 * 3 + 1], 8.0f);
    EXPECT_FLOAT_EQ(coor[0 * 3 + 2], 9.0f);

    EXPECT_FLOAT_EQ(coor[3 * 3 + 0], 100.0f); // water serial 102 -> slot 3
    EXPECT_FLOAT_EQ(coor[3 * 3 + 2], 300.0f);

    // Unmapped slots stay untouched at their initialised values.
    EXPECT_FLOAT_EQ(coor[1 * 3 + 0], 0.0f);
    EXPECT_FLOAT_EQ(coor[2 * 3 + 1], 0.0f);
}

TEST(RescorePoolLoader, MissingFileFailsClosed)
{
    std::unordered_map<int,int> m{{1, 0}};
    float coor[3] = {};
    int matched = -1, skipped = -1;
    EXPECT_FALSE(flexaids::load_complex_coor_from_pdb(
        "/nonexistent/rescore_fixture.pdb", m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 0);
    EXPECT_EQ(skipped, 0);
}

TEST(RescorePoolLoader, MalformedCoordinateLineIsSkippedNotFatal)
{
    const std::string pdb =
        "HETATM   10  C1  LIG B   1      notnum  2.000   3.000  1.00  0.00           C\n"
        "HETATM   11  N1  LIG B   1       1.000   2.000   3.000  1.00  0.00           N\n";
    const std::string path = write_temp("rescore_loader_bad.pdb", pdb);
    std::unordered_map<int,int> m{{10, 0}, {11, 1}};
    float coor[2 * 3] = {};
    int matched = -1, skipped = -1;
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 1);   // only the well-formed record lands
    EXPECT_EQ(skipped, 1);   // malformed coordinate line counted and skipped
    EXPECT_FLOAT_EQ(coor[1 * 3 + 0], 1.0f);
    EXPECT_FLOAT_EQ(coor[1 * 3 + 2], 3.0f);
}
