from __future__ import annotations

import math
import shutil
import sys
from pathlib import Path

import pytest
from rdkit import Chem
from rdkit.Chem import AllChem, rdDepictor

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from benchmarks.astex_entropy.models import TargetRecord
from benchmarks.astex_entropy.sdf_utils import read_first_sdf_mol
from benchmarks.astex_entropy.tools import (
    _collect_flexaidds_records,
    _file_sha256,
    _write_pose_with_reference_topology,
)
from benchmarks.astex_entropy.validation import rmsd_to_reference


def _write_reference_sdf(path: Path, smiles: str, *, embed_3d: bool = False) -> Chem.Mol:
    molecule = Chem.AddHs(Chem.MolFromSmiles(smiles))
    if embed_3d:
        assert AllChem.EmbedMolecule(molecule, randomSeed=0xC0FFEE) == 0
    else:
        rdDepictor.Compute2DCoords(molecule)
        Chem.WedgeMolBonds(molecule, molecule.GetConformer())
    writer = Chem.SDWriter(str(path))
    writer.write(molecule)
    writer.close()
    return read_first_sdf_mol(path, allow_unsanitized=True)


def _pdb_atom_line(
    record: str,
    serial: int,
    atom_name: str,
    residue_name: str,
    residue_number: int,
    xyz: tuple[float, float, float],
    element: str,
) -> str:
    x, y, z = xyz
    line = (
        f"{record:<6}{serial:5d} {atom_name:<4.4s} {residue_name:>3.3s} A{residue_number:4d}    "
        f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {element:>2.2s}"
    )
    assert line[76:78].strip() == element
    return line


def _write_flexaidds_pose(
    path: Path,
    molecule: Chem.Mol,
    coordinates: list[tuple[float, float, float]],
    *,
    atom_count: int | None = None,
    atomic_numbers: list[int] | None = None,
) -> None:
    count = molecule.GetNumAtoms() if atom_count is None else atom_count
    periodic_table = Chem.GetPeriodicTable()
    numbers = atomic_numbers or [atom.GetAtomicNum() for atom in molecule.GetAtoms()]
    lines = [
        "REMARK coordinate file generated by FlexAID",
        _pdb_atom_line("ATOM", 1, "CA", "ALA", 1, (0.0, 0.0, 0.0), "C"),
        _pdb_atom_line("HETATM", 50000, "O", "HOH", 2, (2.0, 2.0, 2.0), "O"),
    ]
    for index in range(count):
        symbol = periodic_table.GetElementSymbol(numbers[index])
        lines.append(
            _pdb_atom_line(
                "HETATM",
                90001 + index,
                f"{symbol}{index}",
                "LIG",
                9999,
                coordinates[index],
                symbol,
            )
        )
    for index in range(count):
        neighbours = sorted(
            90001 + neighbour.GetIdx()
            for neighbour in molecule.GetAtomWithIdx(index).GetNeighbors()
            if neighbour.GetIdx() < count
        )
        lines.append(f"CONECT{90001 + index:5d}" + "".join(f"{serial:5d}" for serial in neighbours))
    lines.append("END")
    path.write_text("\n".join(lines) + "\n")


def _graph_signature(molecule: Chem.Mol) -> tuple[tuple[object, ...], tuple[object, ...]]:
    atoms = tuple(
        (
            atom.GetAtomicNum(),
            atom.GetFormalCharge(),
            int(atom.GetChiralTag()),
            atom.GetIsAromatic(),
        )
        for atom in molecule.GetAtoms()
    )
    bonds = tuple(
        sorted(
            (
                min(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()),
                max(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()),
                str(bond.GetBondType()),
                bond.GetIsAromatic(),
                int(bond.GetStereo()),
                tuple(bond.GetStereoAtoms()),
            )
            for bond in molecule.GetBonds()
        )
    )
    return atoms, bonds


def _translated_coordinates(
    molecule: Chem.Mol,
    delta: tuple[float, float, float] = (8.0, -3.0, 2.0),
) -> list[tuple[float, float, float]]:
    conformer = molecule.GetConformer()
    dx, dy, dz = delta
    return [
        (
            conformer.GetAtomPosition(index).x + dx,
            conformer.GetAtomPosition(index).y + dy,
            conformer.GetAtomPosition(index).z + dz,
        )
        for index in range(molecule.GetNumAtoms())
    ]


def test_reference_topology_transfer_preserves_full_graph_charge_stereo_and_coordinates(
    tmp_path: Path,
) -> None:
    reference_sdf = tmp_path / "reference.sdf"
    reference = _write_reference_sdf(
        reference_sdf,
        "[NH3+][C@@H](CCl)C(=O)[O-]",
        embed_3d=True,
    )
    coordinates = _translated_coordinates(reference)
    pose_pdb = tmp_path / "pose.pdb"
    pose_sdf = tmp_path / "pose.sdf"
    _write_flexaidds_pose(pose_pdb, reference, coordinates)

    _write_pose_with_reference_topology(pose_pdb, reference_sdf, pose_sdf)

    pose = read_first_sdf_mol(pose_sdf, allow_unsanitized=True)
    assert pose.GetNumAtoms() == reference.GetNumAtoms()
    assert pose.GetNumAtoms() > sum(atom.GetAtomicNum() > 1 for atom in pose.GetAtoms())
    assert _graph_signature(pose) == _graph_signature(reference)
    assert [atom.GetFormalCharge() for atom in pose.GetAtoms()] == [
        atom.GetFormalCharge() for atom in reference.GetAtoms()
    ]
    assert any(atom.GetChiralTag() != Chem.ChiralType.CHI_UNSPECIFIED for atom in pose.GetAtoms())
    conformer = pose.GetConformer()
    for index, expected in enumerate(coordinates):
        actual = conformer.GetAtomPosition(index)
        assert (actual.x, actual.y, actual.z) == pytest.approx(expected, abs=1e-3)


@pytest.mark.parametrize("mismatch", ["count", "element"])
def test_reference_topology_transfer_fails_closed_on_atom_mismatch(
    tmp_path: Path,
    mismatch: str,
) -> None:
    reference_sdf = tmp_path / "reference.sdf"
    reference = _write_reference_sdf(reference_sdf, "CC(=O)N")
    coordinates = _translated_coordinates(reference)
    pose_pdb = tmp_path / f"{mismatch}.pdb"
    pose_sdf = tmp_path / f"{mismatch}.sdf"
    kwargs: dict[str, object] = {}
    expected_message = "atom-count mismatch"
    if mismatch == "count":
        kwargs["atom_count"] = reference.GetNumAtoms() - 1
    else:
        numbers = [atom.GetAtomicNum() for atom in reference.GetAtoms()]
        mismatch_index = next(index for index, number in enumerate(numbers) if number != 7)
        numbers[mismatch_index] = 7
        kwargs["atomic_numbers"] = numbers
        expected_message = "atomic-number mismatch"
    _write_flexaidds_pose(pose_pdb, reference, coordinates, **kwargs)
    pose_sdf.write_text("stale output must not survive a failed transfer\n")

    with pytest.raises(RuntimeError, match=expected_message):
        _write_pose_with_reference_topology(pose_pdb, reference_sdf, pose_sdf)
    assert not pose_sdf.exists()


def test_reference_topology_transfer_preserves_aromatic_ring_and_amide(tmp_path: Path) -> None:
    reference_sdf = tmp_path / "acetanilide.sdf"
    reference = _write_reference_sdf(reference_sdf, "CC(=O)Nc1ccccc1")
    pose_pdb = tmp_path / "acetanilide_pose.pdb"
    pose_sdf = tmp_path / "acetanilide_pose.sdf"
    _write_flexaidds_pose(pose_pdb, reference, _translated_coordinates(reference))

    _write_pose_with_reference_topology(pose_pdb, reference_sdf, pose_sdf)

    pose = read_first_sdf_mol(pose_sdf, allow_unsanitized=True)
    assert _graph_signature(pose) == _graph_signature(reference)
    assert sum(atom.GetIsAromatic() for atom in pose.GetAtoms()) == 6
    assert sum(bond.GetIsAromatic() for bond in pose.GetBonds()) == 6
    amide = Chem.MolFromSmarts("[CX3](=[OX1])-[NX3]")
    carbon, _, nitrogen = pose.GetSubstructMatch(amide)
    assert pose.GetBondBetweenAtoms(carbon, nitrogen).GetBondType() == Chem.BondType.SINGLE


def test_duplicate_pose_files_are_identified_by_sha256_not_inode(tmp_path: Path) -> None:
    reference_sdf = tmp_path / "reference.sdf"
    reference = _write_reference_sdf(reference_sdf, "CCO")
    result_dir = tmp_path / "flexaidds" / "native" / "TST1"
    result_dir.mkdir(parents=True)
    elected = result_dir / "elected_pose.pdb"
    duplicate = result_dir / "TST1_pose_001.pdb"
    _write_flexaidds_pose(elected, reference, _translated_coordinates(reference))
    shutil.copyfile(elected, duplicate)
    assert elected.stat().st_ino != duplicate.stat().st_ino
    assert _file_sha256(elected) == _file_sha256(duplicate)

    target = TargetRecord(
        target_id="TST1",
        mode="native",
        receptor_pdb=str(tmp_path / "receptor.pdb"),
        ligand_sdf=str(reference_sdf),
        reference_sdf=str(reference_sdf),
    )
    cfg = {
        "work_dir": str(tmp_path),
        "tools": {"flexaidds": {"score_direction": "lower"}},
    }
    records = _collect_flexaidds_records([target], cfg, "native")

    assert len(records) == 1
    assert records[0].source_file == str(elected)
    assert Path(records[0].pose_sdf).is_file()
    assert not list(tmp_path.rglob("*.obabel.log"))


@pytest.mark.parametrize("target_id", ["1OF6", "1M2Z"])
def test_repo_astex_reference_validator_only_export_smoke(
    tmp_path: Path,
    target_id: str,
) -> None:
    reference_sdf = (
        REPO_ROOT
        / "benchmarks"
        / "astex_diverse"
        / "data"
        / "astex_diverse"
        / target_id
        / f"{target_id}_ligand.sdf"
    )
    reference = read_first_sdf_mol(reference_sdf, allow_unsanitized=True)
    delta = (8.0, -3.0, 2.0)
    coordinates = _translated_coordinates(reference, delta)
    pose_pdb = tmp_path / f"{target_id}_pose.pdb"
    pose_sdf = tmp_path / f"{target_id}_pose.sdf"
    _write_flexaidds_pose(pose_pdb, reference, coordinates)

    _write_pose_with_reference_topology(pose_pdb, reference_sdf, pose_sdf)

    pose = read_first_sdf_mol(pose_sdf, allow_unsanitized=True)
    assert _graph_signature(pose) == _graph_signature(reference)
    rmsd = rmsd_to_reference(pose_sdf, reference_sdf)
    assert rmsd is not None
    assert rmsd == pytest.approx(math.sqrt(sum(component**2 for component in delta)), abs=2e-3)
