from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from benchmarks.astex_entropy import tools as tools_mod
from benchmarks.astex_entropy import validation as validation_mod


def _flexaidds_like_complex(atom_count: int = 19) -> str:
    """Synthetic FlexAIDdS write_pdb output with variable-width atom names."""
    lines = ["REMARK coordinate file generated by FlexAID"]
    # Standard protein atom (ignored for ligand extract).
    lines.append(
        "ATOM      1  N   ALA A   1      11.104  13.207   9.628  1.00  0.00           N  "
    )
    # FlexAIDdS-style ligand: serial >= 90000, names "N 0", "C 1", ..., "C 10".
    elements = ["N", "C", "C", "C", "C", "C", "C", "Cl", "S", "C", "C", "C", "O", "O", "C", "C", "C", "C", "N"]
    for i in range(atom_count):
        serial = 90001 + i
        elem = elements[i % len(elements)]
        name = f"{elem}{i}" if len(elem) > 1 else f"{elem} {i}"
        # Intentionally non-fixed-width, matching FlexAIDdS fprintf("%s%5d %s ...").
        lines.append(
            f"HETATM{serial} {name} STC     1      "
            f"{20.0 + i * 0.1:8.3f}{30.0 + i * 0.05:8.3f}{10.0:8.3f}  1.00  0.00          {elem:>2}  "
        )
    # CONECT that references present atoms only for first few, plus one dangling ref.
    lines.append("CONECT9000190002")
    lines.append(f"CONECT90002{90001:5d}{90003:5d}")
    if atom_count >= 3:
        # Dangling CONECT referring to a missing serial — must be dropped.
        lines.append(f"CONECT{90001 + atom_count:5d}{90001:5d}")
    lines.append("END")
    return "\n".join(lines) + "\n"


def _benzene_sdf(coords: list[tuple[float, float, float]] | None = None) -> str:
    if coords is None:
        coords = [
            (0.000, 1.396, 0.000),
            (1.209, 0.698, 0.000),
            (1.209, -0.698, 0.000),
            (0.000, -1.396, 0.000),
            (-1.209, -0.698, 0.000),
            (-1.209, 0.698, 0.000),
        ]
    lines = [
        "benzene",
        "  GrokBuild",
        "",
        f"{len(coords):3d}{len(coords):3d}  0  0  0  0  0  0  0  0999 V2000",
    ]
    for x, y, z in coords:
        lines.append(f"{x:10.4f}{y:10.4f}{z:10.4f} C   0  0  0  0  0  0  0  0  0  0  0  0")
    bonds = [(1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 1)]
    for a, b in bonds[: len(coords)]:
        lines.append(f"{a:3d}{b:3d}  1  0  0  0  0")
    lines.extend(["M  END", "$$$$", ""])
    return "\n".join(lines)


class FlexaiddsLigandExtractP0Tests(unittest.TestCase):
    def test_token_parser_keeps_full_ligand_despite_shifted_columns(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            complex_pdb = Path(tmp) / "complex.pdb"
            ligand_pdb = Path(tmp) / "ligand.pdb"
            complex_pdb.write_text(_flexaidds_like_complex(19))
            ok = tools_mod._extract_flexaidds_ligand_pdb(complex_pdb, ligand_pdb)
            self.assertTrue(ok)
            het = [ln for ln in ligand_pdb.read_text().splitlines() if ln.startswith("HETATM")]
            self.assertEqual(len(het), 19)
            # Fixed-column rewrite must place resname in cols 17:20.
            resnames = {ln[17:20].strip() for ln in het}
            self.assertEqual(resnames, {"STC"})

    def test_conect_drops_absent_serials(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            complex_pdb = Path(tmp) / "complex.pdb"
            ligand_pdb = Path(tmp) / "ligand.pdb"
            complex_pdb.write_text(_flexaidds_like_complex(10))
            tools_mod._extract_flexaidds_ligand_pdb(complex_pdb, ligand_pdb)
            conect = [ln for ln in ligand_pdb.read_text().splitlines() if ln.startswith("CONECT")]
            for line in conect:
                serials = tools_mod._parse_conect_serials(line)
                self.assertTrue(all(90001 <= s <= 90010 for s in serials))

    def test_rejects_truncated_pose_relative_to_reference_count(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            complex_pdb = Path(tmp) / "complex.pdb"
            ref_sdf = Path(tmp) / "ref.sdf"
            complex_pdb.write_text(_flexaidds_like_complex(10))
            # Reference with 19 heavy atoms (synthetic benzene is 6 — use formula count path).
            # Build a simple 19-carbon chain SDF counts line.
            coords = [(float(i), 0.0, 0.0) for i in range(19)]
            lines = [
                "lig",
                "  test",
                "",
                f"{19:3d}{18:3d}  0  0  0  0  0  0  0  0999 V2000",
            ]
            for x, y, z in coords:
                lines.append(f"{x:10.4f}{y:10.4f}{z:10.4f} C   0  0  0  0  0  0  0  0  0  0  0  0")
            for i in range(1, 19):
                lines.append(f"{i:3d}{i + 1:3d}  1  0  0  0  0")
            lines.extend(["M  END", "$$$$", ""])
            ref_sdf.write_text("\n".join(lines))
            atoms, _ = tools_mod._extract_flexaidds_ligand_atoms(
                complex_pdb, reference_sdf=ref_sdf, obabel=None
            )
            self.assertEqual(len(atoms), 10)
            # Topology writer must reject count mismatch.
            pose_sdf = Path(tmp) / "pose.sdf"
            wrote = tools_mod._write_pose_sdf_from_reference_topology(
                atoms, ref_sdf, pose_sdf, obabel=None
            )
            self.assertFalse(wrote)


class WholeLigandRmsdP0Tests(unittest.TestCase):
    def test_truncated_pose_has_no_success_rmsd_but_may_have_mcs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            ref = Path(tmp) / "ref.sdf"
            pose = Path(tmp) / "pose.sdf"
            ref.write_text(_benzene_sdf())
            # Truncated 3-atom fragment of benzene-like coords.
            pose.write_text(
                _benzene_sdf(
                    [
                        (0.000, 1.396, 0.000),
                        (1.209, 0.698, 0.000),
                        (1.209, -0.698, 0.000),
                    ]
                )
            )
            diag = validation_mod.rmsd_diagnostics(pose, ref)
            self.assertFalse(diag["whole_ligand"])
            self.assertIsNone(diag["rmsd_A"])
            self.assertIsNone(validation_mod.rmsd_to_reference(pose, ref))
            # MCS diagnostic may exist; must not become rmsd_A.
            if diag["fragment_mcs_rmsd_A"] is not None:
                self.assertLess(diag["fragment_mcs_rmsd_A"], 2.0)

    def test_complete_pose_reports_whole_ligand_rmsd(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            ref = Path(tmp) / "ref.sdf"
            pose = Path(tmp) / "pose.sdf"
            ref.write_text(_benzene_sdf())
            # Slightly translated copy — still whole-ligand.
            pose.write_text(
                _benzene_sdf(
                    [
                        (0.100, 1.396, 0.000),
                        (1.309, 0.698, 0.000),
                        (1.309, -0.698, 0.000),
                        (0.100, -1.396, 0.000),
                        (-1.109, -0.698, 0.000),
                        (-1.109, 0.698, 0.000),
                    ]
                )
            )
            diag = validation_mod.rmsd_diagnostics(pose, ref)
            self.assertTrue(diag["whole_ligand"])
            self.assertIsNotNone(diag["rmsd_A"])
            self.assertLess(diag["rmsd_A"], 0.5)


class PoseBustersCacheP0Tests(unittest.TestCase):
    def test_cache_invalidates_when_pose_mtime_changes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            pose = tmp_path / "pose.sdf"
            ref = tmp_path / "ref.sdf"
            receptor = tmp_path / "receptor.pdb"
            pose.write_text(_benzene_sdf())
            ref.write_text(_benzene_sdf())
            receptor.write_text(
                "ATOM      1  N   ALA A   1      11.104  13.207   9.628  1.00  0.00           N  \nEND\n"
            )

            scratch = tmp_path / "scratch"
            scratch.mkdir()
            out_csv = scratch / "posebusters.csv"
            meta_path = scratch / "posebusters.cache.json"
            # Minimal valid PoseBusters-like CSV (all checks true).
            out_csv.write_text("molecule,mol_pred,bond_lengths\npose,pose,True\n")

            pose_fp = validation_mod._file_fingerprint(pose)
            expected = {
                "version": 1,
                "pose_sdf": pose_fp,
                "reference_sdf": validation_mod._file_fingerprint(ref),
                "receptor_pdb": validation_mod._file_fingerprint(receptor),
                "pose_input": pose_fp,
                "reference_input": validation_mod._file_fingerprint(ref),
                "posebusters_executable": {"path": "bust", "mtime_ns": -1, "size": -1},
                "command_template": "{posebusters} {pose_sdf}",
                "command_args": ["bust", str(pose)],
                "posebusters_config": "redock",
            }
            meta_path.write_text(json.dumps(expected))
            self.assertTrue(
                validation_mod._posebusters_cache_is_valid(meta_path, expected, out_csv, scratch / "posebusters.json")
            )

            # Change pose content/mtime → fingerprints diverge.
            pose.write_text(_benzene_sdf([(0.1, 1.4, 0.0)] * 6))
            stale = dict(expected)
            stale["pose_sdf"] = pose_fp  # old fingerprint
            self.assertFalse(
                validation_mod._posebusters_cache_is_valid(
                    meta_path,
                    {
                        **expected,
                        "pose_sdf": validation_mod._file_fingerprint(pose),
                        "pose_input": validation_mod._file_fingerprint(pose),
                    },
                    out_csv,
                    scratch / "posebusters.json",
                )
            )


if __name__ == "__main__":
    unittest.main()
