// =============================================================================
// test_rescore_pool_loader.cpp — serial-mapped complex coordinate loader.
//
// The offline pool rescoring engine (LIB/rescore_pool.cpp, hooked in top.cpp
// via FLEXAIDDS_RESCORE_POOL) restores FULL-complex coordinates from emitted
// pose files so optimisable DoF on both sides (receptor side chains + ligand
// torsions) are honoured exactly as docked. Correctness of the serial-to-slot
// mapping is therefore load-bearing: a swapped pair would silently rescore
// against wrong geometry. These tests pin the mapping contract on the inline
// loader (flexaids::load_complex_coor_from_pdb) with no engine state needed.
//
// Apache-2.0 (c) 2026 Le Bonhomme Pharma
// =============================================================================

// gtest FIRST: flexaid.h leaks macros (e.g. #define E) that break gtest
// internals otherwise — same pattern as tests/test_dataset_runner.cpp.
#include <gtest/gtest.h>

#include "rescore_pool.h"

#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>
#include <sys/stat.h>
#include <unordered_map>

namespace {

const char* kPosePdb =
    "REMARK coordinate file generated by FlexAID\n"
    "ATOM      1  N   ALA A  42       1.000   2.000   3.000  1.00  0.00           N\n"
    "ATOM      5  CA  ALA A  42       4.000  -5.000   6.000  1.00  0.00           C\n"
    "HETATM  100  C1  LIG B   1      -7.000   8.000   9.000  1.00  0.00           C\n"
    "HETATM  101  O1  LIG B   1     -10.000 -11.000  12.000  1.00  0.00           O\n"
    "HETATM  102  O   HOH B  99     100.000 200.000 300.000  1.00  0.00           O\n"
    "CONECT  100  101\n"
    "END\n";

std::string write_temp(const std::string& name, const std::string& content)
{
    const char* td = std::getenv("TMPDIR");
    const std::string path =
        std::string(td && td[0] ? td : "/tmp") + "/" + name;
    std::ofstream ofs(path);
    ofs << content;
    return path;
}

} // namespace

TEST(RescorePoolLoader, MapsSerialsToSlotsAndSkipsUnknowns)
{
    // Deliberately sparse map: serial 5 is unmapped and must be SKIPPED, not
    // silently compacted — a compaction bug would shift every later atom.
    std::unordered_map<int,int> m{{1, 7}, {100, 0}, {102, 3}};
    float coor[8 * 3] = {};  // slot 7 is in-range; 4 slots would OOB under ASan
    int matched = -1, skipped = -1;

    const std::string path = write_temp("rescore_loader_ok.pdb", kPosePdb);
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));

    EXPECT_EQ(matched, 3);
    EXPECT_EQ(skipped, 2);  // serial 5 unmapped + CONECT/END are not atom lines

    EXPECT_FLOAT_EQ(coor[7 * 3 + 0], 1.0f);   // serial 1 -> slot 7
    EXPECT_FLOAT_EQ(coor[7 * 3 + 1], 2.0f);
    EXPECT_FLOAT_EQ(coor[7 * 3 + 2], 3.0f);

    EXPECT_FLOAT_EQ(coor[0 * 3 + 0], -7.0f);  // serial 100 -> slot 0
    EXPECT_FLOAT_EQ(coor[0 * 3 + 1], 8.0f);
    EXPECT_FLOAT_EQ(coor[0 * 3 + 2], 9.0f);

    EXPECT_FLOAT_EQ(coor[3 * 3 + 0], 100.0f); // water serial 102 -> slot 3
    EXPECT_FLOAT_EQ(coor[3 * 3 + 2], 300.0f);

    // Unmapped slots stay untouched at their initialised values.
    EXPECT_FLOAT_EQ(coor[1 * 3 + 0], 0.0f);
    EXPECT_FLOAT_EQ(coor[2 * 3 + 1], 0.0f);
}

TEST(RescorePoolLoader, MissingFileFailsClosed)
{
    std::unordered_map<int,int> m{{1, 0}};
    float coor[3] = {};
    int matched = -1, skipped = -1;
    EXPECT_FALSE(flexaids::load_complex_coor_from_pdb(
        "/nonexistent/rescore_fixture.pdb", m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 0);
    EXPECT_EQ(skipped, 0);
}

TEST(RescorePoolLoader, MalformedCoordinateLineIsSkippedNotFatal)
{
    const std::string pdb =
        "HETATM   10  C1  LIG B   1      notnum  2.000   3.000  1.00  0.00           C\n"
        "HETATM   11  N1  LIG B   1       1.000   2.000   3.000  1.00  0.00           N\n";
    const std::string path = write_temp("rescore_loader_bad.pdb", pdb);
    std::unordered_map<int,int> m{{10, 0}, {11, 1}};
    float coor[2 * 3] = {};
    int matched = -1, skipped = -1;
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 1);   // only the well-formed record lands
    EXPECT_EQ(skipped, 1);   // malformed coordinate line counted and skipped
    EXPECT_FLOAT_EQ(coor[1 * 3 + 0], 1.0f);
    EXPECT_FLOAT_EQ(coor[1 * 3 + 2], 3.0f);
}


// ── Adversarial hardening suite (worst-case pool files) ─────────────────────

TEST(RescorePoolLoader, OutOfIntRangeSerialDoesNotPoisonMappedSlot)
{
    // 5-column parse of HETATM4294967297 is 42949. Put that key in the map so
    // accepting the truncated prefix would write -9 into slot 2.
    const std::string pdb =
        "HETATM   1  N1  LIG B   1       1.000   2.000   3.000  1.00  0.00           N\n"
        "HETATM4294967297  XX  LIG B   1     -9.000  -9.000  -9.000  1.00  0.00           C\n";
    const std::string path = write_temp("rescore_overflow.pdb", pdb);
    std::unordered_map<int,int> m{{1, 5}, {42949, 2}};
    float coor[6 * 3] = {};
    int matched = -1, skipped = -1;
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 1);
    EXPECT_EQ(skipped, 1);  // overlong serial field is refused, not truncated
    EXPECT_FLOAT_EQ(coor[5 * 3 + 0], 1.0f);
    EXPECT_FLOAT_EQ(coor[5 * 3 + 1], 2.0f);
    EXPECT_FLOAT_EQ(coor[2 * 3 + 0], 0.0f);  // collision slot stays empty
}

TEST(RescorePoolLoader, NegativeSerialIsSkipped)
{
    const std::string pdb =
        "HETATM  -7  X1  LIG B   1       9.000   9.000   9.000  1.00  0.00           C\n"
        "HETATM   2  N1  LIG B   1       1.000   1.000   1.000  1.00  0.00           N\n";
    const std::string path = write_temp("rescore_neg.pdb", pdb);
    // Include -7 so a loader that only skips unmapped keys would write slot 1.
    std::unordered_map<int,int> m{{2, 0}, {-7, 1}};
    float coor[2 * 3] = {};
    int matched = -1, skipped = -1;
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 1);
    EXPECT_EQ(skipped, 1);
    EXPECT_FLOAT_EQ(coor[0], 1.0f);
    EXPECT_FLOAT_EQ(coor[1 * 3 + 0], 0.0f);
}

TEST(RescorePoolLoader, DuplicateSerialsLastWriteWinsAndCountsBoth)
{
    // Real pools should never contain duplicates; if one appears the loader's
    // contract is deterministic: both records count as matched and the LAST
    // occurrence owns the slot (documented, not silent corruption).
    const std::string pdb =
        "HETATM   1  C1  LIG B   1       1.000   1.000   1.000  1.00  0.00           C\n"
        "HETATM   1  C1  LIG B   1       2.000   2.000   2.000  1.00  0.00           C\n";
    const std::string path = write_temp("rescore_dup.pdb", pdb);
    std::unordered_map<int,int> m{{1, 2}};
    float coor[3 * 3] = {};   // slot 2 -> needs indices 6..8
    int matched = -1, skipped = -1;
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 2);                 // every occurrence counts
    EXPECT_FLOAT_EQ(coor[2 * 3 + 0], 2.0f);// LAST occurrence owns the slot
    EXPECT_FLOAT_EQ(coor[2 * 3 + 1], 2.0f);
    EXPECT_FLOAT_EQ(coor[2 * 3 + 2], 2.0f);
    EXPECT_FLOAT_EQ(coor[0], 0.0f);        // other slots untouched
}

TEST(RescorePoolLoader, EmptyAndNoAtomFilesParseToZero)
{
    {
        const std::string path = write_temp("rescore_empty.pdb", "");
        std::unordered_map<int,int> m{{1, 0}};
        float coor[3] = {9.f, 9.f, 9.f};
        int matched = -1, skipped = -1;
        ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
            path.c_str(), m, coor, &matched, &skipped));
        EXPECT_EQ(matched, 0);
        EXPECT_EQ(skipped, 0);
        EXPECT_FLOAT_EQ(coor[0], 9.f);  // untouched initialiser survives
    }
    {
        const std::string path = write_temp(
            "rescore_noatom.pdb", "REMARK nothing here\nEND\n");
        std::unordered_map<int,int> m{{1, 0}};
        float coor[3] = {};
        int matched = -1, skipped = -1;
        ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
            path.c_str(), m, coor, &matched, &skipped));
        EXPECT_EQ(matched, 0);
    }
}

TEST(RescorePoolLoader, OverlongLineDrainedWithoutPhantomRecords)
{
    // 600-char record line: fgets(512) splits it. Contract: the physical line
    // is accounted ONCE (its parseable prefix still lands coordinates), and
    // the drained tail must never resurface as a phantom atom record.
    std::string long_body(600, 'A');
    const std::string pdb =
        "HETATM   1  C1  LIG B   1       1.000   2.000   3.000  1.00  0.00" +
        long_body + "\n"
        "HETATM   2  N1  LIG B   1       4.000   5.000   6.000  1.00  0.00           N\n";
    const std::string path = write_temp("rescore_long.pdb", pdb);
    std::unordered_map<int,int> m{{1, 0}, {2, 1}};
    float coor[2 * 3] = {};
    int matched = -1, skipped = -1;
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));
    EXPECT_EQ(skipped, 0);   // prefix carried valid coordinates: not skipped
    EXPECT_EQ(matched, 2);   // serial 1 once (not twice!) + serial 2
                             // a phantom re-parse of the tail would make this 3
    EXPECT_FLOAT_EQ(coor[0 * 3 + 0], 1.0f);
    EXPECT_FLOAT_EQ(coor[0 * 3 + 2], 3.0f);
    EXPECT_FLOAT_EQ(coor[1 * 3 + 0], 4.0f);
    EXPECT_FLOAT_EQ(coor[1 * 3 + 2], 6.0f);
}

TEST(RescorePoolLoader, CrlfLineEndingsAccepted)
{
    const std::string pdb =
        "HETATM   1  C1  LIG B   1       1.500   2.500   3.500  1.00  0.00           C\r\n";
    const std::string path = write_temp("rescore_crlf.pdb", pdb);
    std::unordered_map<int,int> m{{1, 0}};
    float coor[3] = {};
    int matched = -1, skipped = -1;
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 1);
    EXPECT_FLOAT_EQ(coor[0], 1.5f);
    EXPECT_FLOAT_EQ(coor[2], 3.5f);
}

TEST(RescorePoolLoader, Utf8BomBeforeFirstRecordHandled)
{
    const std::string pdb =
        "\xEF\xBB\xBF"
        "HETATM   1  C1  LIG B   1       7.000   8.000   9.000  1.00  0.00           C\n";
    const std::string path = write_temp("rescore_bom.pdb", pdb);
    std::unordered_map<int,int> m{{1, 4}};
    float coor[5 * 3] = {};
    int matched = -1, skipped = -1;
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 1);
    EXPECT_EQ(skipped, 0);
    EXPECT_FLOAT_EQ(coor[4 * 3 + 0], 7.0f);
}

TEST(RescorePoolLoader, PartialSerialFieldIsRejected)
{
    // Columns 7–11 are "   1A". strtol would yield 1; map serial 1 so a
    // prefix-accepting loader would write slot 0.
    const std::string pdb =
        "HETATM   1A C1  LIG B   1       9.000   9.000   9.000  1.00  0.00           C\n"
        "HETATM   2  N1  LIG B   1       1.000   1.000   1.000  1.00  0.00           N\n";
    const std::string path = write_temp("rescore_partial_serial.pdb", pdb);
    std::unordered_map<int,int> m{{1, 0}, {2, 1}};
    float coor[2 * 3] = {};
    int matched = -1, skipped = -1;
    ASSERT_TRUE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 1);
    EXPECT_EQ(skipped, 1);
    EXPECT_FLOAT_EQ(coor[0], 0.0f);
    EXPECT_FLOAT_EQ(coor[1 * 3 + 0], 1.0f);
}

TEST(RescorePoolLoader, UnreadableFileFailsClosed)
{
    const std::string path = write_temp("rescore_unreadable.pdb",
                                        "HETATM   1  C   LIG B   1       0.000   0.000   0.000\n");
    ::chmod(path.c_str(), 0000);
    if (FILE* probe = std::fopen(path.c_str(), "r")) {
        std::fclose(probe);
        ::chmod(path.c_str(), 0644);
        GTEST_SKIP() << "process can open chmod 000 files (privileged); "
                        "EACCES path is not testable here";
    }
    std::unordered_map<int,int> m{{1, 0}};
    float coor[3] = {};
    int matched = -1, skipped = -1;
    EXPECT_FALSE(flexaids::load_complex_coor_from_pdb(
        path.c_str(), m, coor, &matched, &skipped));
    EXPECT_EQ(matched, 0);
    ::chmod(path.c_str(), 0644);  // allow removal on teardown
}
