// RunReceipt.h — Campaign / DatasetRunner RUN_RECEIPT.json provenance
//
// Aligns the C++ DatasetRunner path with C0 iCloud launch scripts
// (RUN_RECEIPT.json schema: matrix/binary hashes, GA knobs, ProtocolConfig).
//
// Copyright 2026 Le Bonhomme Pharma. Licensed under Apache-2.0.
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include "ProtocolConfig.h"

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace flexaids {

/// Inputs for a campaign/run receipt. Hash fields may be precomputed or left
/// empty for the writer to fill when paths exist.
struct RunReceiptInput {
    std::string run_id;
    std::string started_utc;   ///< ISO-8601 UTC, e.g. 2026-07-15T02:54:52Z
    std::string output;
    std::string dataset;
    std::string mode;          ///< e.g. defined-cleft-redock
    double temperature_K{300.0};
    int pop{1000};
    int gen{2000};
    int restarts{5};
    std::uint64_t seed_base{0};
    bool seed_elitism{true};

    std::string matrix_path;
    std::string matrix_md5;
    std::string matrix_sha256;
    std::string binary_path;
    std::string binary_sha256;
    std::string runner_path;
    std::string runner_sha256;
    std::string git_commit;
    std::string oracle_site_dir;
    bool oracle_site_dir_set{false};

    // ── The roster this run ACTUALLY executed, and the source it claims to ──
    // implement. Everything above this block describes HOW the run was
    // configured; none of it recorded WHAT set of targets was enumerated. A
    // roster that was 72/85 of the published Astex Diverse Set ran for months and
    // no receipt it wrote could have contradicted the claim that it was the
    // published set, because the executed list was never written down.
    //
    // executed_codes is what the runner enumerated, in order. The sidecar file is
    // the same list as newline-terminated text, and executed_codes_sha256 is that
    // file's sha256 -- so the digest is over a real artifact anyone can rehash,
    // computed by the same code path as matrix_sha256 and binary_sha256.
    //
    // dataset_source_* come from LIB/generated/dataset_codes.inc (generated by
    // scripts/gen_dataset_codes.py), so they name the file the code list was
    // GENERATED from rather than a path someone typed into a config.
    // scripts/check_run_receipt_codes.py is the validator that fails a run whose
    // executed list does not match its declared source.
    std::vector<std::string> executed_codes;   ///< enumerated roster, in run order
    std::string executed_codes_file;           ///< sidecar path (executed_codes.txt)
    std::string executed_codes_sha256;         ///< sha256 of that sidecar
    std::size_t declared_codes_count{0};       ///< count in the canonical source
    std::string dataset_source_path;           ///< repo-relative canonical source
    std::string dataset_source_sha256;         ///< source sha256 at codegen time
    std::string dataset_source_provenance;     ///< ROSTER_CSV|DEFINITION_YAML|EXTRACTED_FROM_CODE
    std::string dataset_source_primary;        ///< primary-source DOI, or UNVERIFIED

    ProtocolConfig protocol;
};

/// schema_version for RUN_RECEIPT.json.
/// 1 -> 2: added executed_codes / executed_codes_sha256 / dataset_source_*. The
/// bump is what lets scripts/check_run_receipt_codes.py tell a pre-S2 receipt
/// (UNCHECKABLE, no roster recorded) apart from a schema-2 receipt with those
/// fields stripped (FAIL). Without it, a tampered receipt is indistinguishable
/// from an old one.
inline constexpr int kRunReceiptSchemaVersion = 2;

/// Build a JSON object string (pretty-printed, trailing newline not included).
[[nodiscard]] std::string build_run_receipt_json(const RunReceiptInput& in);

/// Write RUN_RECEIPT.json (and optional legacy provenance.json) under output_dir.
/// Returns true if RUN_RECEIPT.json was written successfully.
bool write_run_receipt(const std::string& output_dir,
                       const RunReceiptInput& in,
                       bool also_write_provenance_json = true);

/// Current UTC time as YYYY-MM-DDTHH:MM:SSZ (best-effort; empty on failure).
[[nodiscard]] std::string utc_now_iso8601();

}  // namespace flexaids
