# CMake generated Testfile for 
# Source directory: /Users/lp.more/Projects/FlexAIDdS
# Build directory: /Users/lp.more/Projects/FlexAIDdS/WRK
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[StatMechTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_statmech")
set_tests_properties([=[StatMechTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1110;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[JsonConfigTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_json_config")
set_tests_properties([=[JsonConfigTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1122;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[MetalCoordinationTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_metal_coordination")
set_tests_properties([=[MetalCoordinationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1134;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[FormalChargeTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_formal_charges")
set_tests_properties([=[FormalChargeTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1146;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[HardwareDispatchTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_hardware_dispatch")
set_tests_properties([=[HardwareDispatchTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1174;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[HardwareDetectDispatchTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_hardware_detect_dispatch")
set_tests_properties([=[HardwareDetectDispatchTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1211;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[TENCoMDiffTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_tencom_diff")
set_tests_properties([=[TENCoMDiffTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1242;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[PTMAttachmentTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_ptm_attachment")
set_tests_properties([=[PTMAttachmentTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1260;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[GABoomTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_gaboom")
set_tests_properties([=[GABoomTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1307;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[ShannonGATests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_shannon_ga")
set_tests_properties([=[ShannonGATests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1355;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[VcontactsTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_vcontacts")
set_tests_properties([=[VcontactsTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1375;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[VcontactsGeometryTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_vcontacts_geometry")
set_tests_properties([=[VcontactsGeometryTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1395;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[CleftCavityTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_cleft_cavity")
set_tests_properties([=[CleftCavityTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1418;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[ENCoMTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_encom")
set_tests_properties([=[ENCoMTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1435;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[RingConformerLibraryTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_ring_conformer_library")
set_tests_properties([=[RingConformerLibraryTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1453;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[SugarPuckerTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_sugar_pucker")
set_tests_properties([=[SugarPuckerTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1474;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[ChiralCenterTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_chiral_center")
set_tests_properties([=[ChiralCenterTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1495;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[CavityDetectTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_cavity_detect")
set_tests_properties([=[CavityDetectTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1517;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[MIFGridTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_mif_grid")
set_tests_properties([=[MIFGridTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1537;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[RefLigSpectrophoreTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_reflig_spectrophore")
set_tests_properties([=[RefLigSpectrophoreTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1556;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[BindingResiduesTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_binding_residues")
set_tests_properties([=[BindingResiduesTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1577;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[BindingModeStatMechTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_binding_mode_statmech")
set_tests_properties([=[BindingModeStatMechTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1623;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[CCBMTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_ccbm")
set_tests_properties([=[CCBMTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1669;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[BindingModeAdvancedTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_binding_mode_advanced")
set_tests_properties([=[BindingModeAdvancedTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1715;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[GACoreTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_ga_core")
set_tests_properties([=[GACoreTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1761;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[GAValidationTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_ga_validation")
set_tests_properties([=[GAValidationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1807;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[GAOperatorsTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_ga_operators")
set_tests_properties([=[GAOperatorsTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1852;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[BindingModeComparisonTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_binding_mode_comparison")
set_tests_properties([=[BindingModeComparisonTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1897;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[SoftContactMatrixTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_soft_contact_matrix")
set_tests_properties([=[SoftContactMatrixTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1928;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[CompareEnergyMatricesTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_compare_energy_matrices")
set_tests_properties([=[CompareEnergyMatricesTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1953;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[IonHandlingTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_ion_handling")
set_tests_properties([=[IonHandlingTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;1973;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[EntropyGATests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_entropy_ga")
set_tests_properties([=[EntropyGATests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2017;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[CubeGridTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_cube_grid")
set_tests_properties([=[CubeGridTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2031;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[ParallelDockTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_parallel_dock")
set_tests_properties([=[ParallelDockTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2057;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[KnowledgePoolTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_knowledge_pool")
set_tests_properties([=[KnowledgePoolTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2074;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[Mol2SdfReaderTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_mol2_sdf_reader")
set_tests_properties([=[Mol2SdfReaderTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2088;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[TurboQuantTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_turboquant")
set_tests_properties([=[TurboQuantTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2106;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[DatasetRunnerTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_dataset_runner")
set_tests_properties([=[DatasetRunnerTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2128;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[BindingModeVibrationalTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_binding_mode_vibrational")
set_tests_properties([=[BindingModeVibrationalTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2174;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[FastOPTICSTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_fast_optics")
set_tests_properties([=[FastOPTICSTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2189;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[TencomEntropyDiffTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_tencom_entropy_diff")
set_tests_properties([=[TencomEntropyDiffTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2217;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[TargetValidationTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_target_validation")
set_tests_properties([=[TargetValidationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2233;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[GrandPartitionTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_grand_partition")
set_tests_properties([=[GrandPartitionTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2259;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[TargetServerTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_target_server")
set_tests_properties([=[TargetServerTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2288;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[MultiSiteGPFTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_multi_site_gpf")
set_tests_properties([=[MultiSiteGPFTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2314;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[GISTHBondTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_gist_hbond")
set_tests_properties([=[GISTHBondTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2327;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[HBondPotentialTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_hbond_potential")
set_tests_properties([=[HBondPotentialTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2343;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[GISTGridTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_gist_grid")
set_tests_properties([=[GISTGridTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2358;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[GADiversityTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_ga_diversity")
set_tests_properties([=[GADiversityTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2373;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[SoAConversionTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_soa_conversion")
set_tests_properties([=[SoAConversionTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2389;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[DistributedBackendTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_distributed_backend")
set_tests_properties([=[DistributedBackendTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2404;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
add_test([=[GAContextTests]=] "/Users/lp.more/Projects/FlexAIDdS/WRK/test_ga_context")
set_tests_properties([=[GAContextTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;2424;add_test;/Users/lp.more/Projects/FlexAIDdS/CMakeLists.txt;0;")
subdirs("LIB")
subdirs("python")
subdirs("_deps/googletest-build")
