"""Unit tests for scripts/audit_native_cf.py REMARK CF parsing and pathology."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

# Load scripts/audit_native_cf.py without requiring package install.
_REPO = Path(__file__).resolve().parents[2]
_SCRIPT = _REPO / "scripts" / "audit_native_cf.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("audit_native_cf", _SCRIPT)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules["audit_native_cf"] = mod
    spec.loader.exec_module(mod)
    return mod


anc = _load_module()


class TestParseCfFromRemarkLines:
    def test_equals_no_space(self):
        lines = ["REMARK CF=-12.50000"]
        assert anc.parse_cf_from_remark_lines(lines) == pytest.approx(-12.5)

    def test_equals_with_space_after(self):
        # FlexAID often pads positive CF: "REMARK CF= 1.02993"
        lines = ["REMARK CF= 1.02993"]
        assert anc.parse_cf_from_remark_lines(lines) == pytest.approx(1.02993)

    def test_colon_delimiter(self):
        lines = ["REMARK CF: -10.5"]
        assert anc.parse_cf_from_remark_lines(lines) == pytest.approx(-10.5)

    def test_space_delimiter(self):
        lines = ["REMARK CF -7.0"]
        assert anc.parse_cf_from_remark_lines(lines) == pytest.approx(-7.0)

    def test_first_cf_wins_not_cf_app(self):
        text = (
            "REMARK coordinate file generated by FlexAID\n"
            "REMARK optimized structure\n"
            "REMARK CF=-73.72798\n"
            "REMARK CF.app=-73.72798\n"
            "REMARK CF.com=-214.81542\n"
        )
        assert anc.parse_cf_from_pdb_text(text) == pytest.approx(-73.72798)

    def test_missing_returns_none(self):
        lines = ["REMARK no score here", "ATOM      1  C"]
        assert anc.parse_cf_from_remark_lines(lines) is None

    def test_scientific_notation(self):
        lines = ["REMARK CF=-1.2e1"]
        assert anc.parse_cf_from_remark_lines(lines) == pytest.approx(-12.0)


class TestPathology:
    def test_decoy_much_better(self):
        # CF_pose=-100, CF_native=-50 → gap=-50 < -5 → pathology
        assert anc.is_pathology(-100.0, -50.0, gap_threshold=5.0) is True

    def test_native_better(self):
        # CF_pose=-40, CF_native=-90 → gap=+50 → not pathology
        assert anc.is_pathology(-40.0, -90.0, gap_threshold=5.0) is False

    def test_small_gap_not_flagged(self):
        assert anc.is_pathology(-52.0, -50.0, gap_threshold=5.0) is False

    def test_missing_values(self):
        assert anc.is_pathology(None, -50.0) is False
        assert anc.is_pathology(-50.0, None) is False


class TestAuditComplexFixture:
    def test_audit_tmp_complex(self, tmp_path: Path):
        """End-to-end on a minimal complex directory fixture."""
        d = tmp_path / "1ABC"
        d.mkdir()
        (d / "1ABC_0.pdb").write_text(
            "REMARK optimized structure\nREMARK CF=-80.0\nEND\n",
            encoding="utf-8",
        )
        (d / "1ABC_INI.pdb").write_text(
            "REMARK initial structure\nREMARK CF=-60.0\nEND\n",
            encoding="utf-8",
        )
        (d / "result.csv").write_text(
            "pdb_id,best_score,cf_native,rmsd_to_crystal,elected_pose\n"
            "1ABC,-80.0,-60.0,3.5,1ABC_0.pdb\n",
            encoding="utf-8",
        )
        row = anc.audit_complex(d, pathology_gap=5.0)
        assert row.pdb_id == "1ABC"
        assert row.cf_pose == pytest.approx(-80.0)
        assert row.cf_native == pytest.approx(-60.0)
        assert row.gap == pytest.approx(-20.0)
        assert row.rmsd == pytest.approx(3.5)
        assert row.pathology is True
        assert "1ABC_0" in row.elected_pose
